version: "3.3"

services:
  nginx:
    depends_on:
      - backend
    restart: always
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    expose:
      - 3050
    ports:
      - "3050:80"
  # frontend:
  #   build: ./frontend
    
  backend:
    build: ./backend
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - 8000:8000
    expose:
      - 8000
      - 8080
    stdin_open: true
    tty: true
